name: TALUltimate
main: com.talultimate.TalUltimatePlugin
version: 1.1.0
api-version: "1.21"
load: POSTWORLD
commands:
  menu: { description: Open main menu, usage: /menu }
  money: { description: Check balance, usage: /money }
  deposit: { description: Deposit notes/ores, usage: /deposit [all|note|<material> <amount>] }
  withdraw: { description: Withdraw notes/coins, usage: /withdraw <amount> }
  sell: { description: Sell items, usage: /sell [hand|all] }
  광장: { description: Warp to plaza }
  결투장: { description: Warp to arena }
  tpa: { description: Send TP request, usage: /tpa <player> }
  tpaccept: { description: Accept TP request }
  tpdeny: { description: Deny TP request }
  sethome: { description: Set home, usage: /sethome [name] }
  home: { description: Go home, usage: /home [name] }
  delhome: { description: Delete home, usage: /delhome [name] }
  addtitle: { description: OP add title to player, permission: tal.admin, usage: /addtitle <player> <titleId> }
  removetitle: { description: OP remove title from player, permission: tal.admin, usage: /removetitle <player> <titleId> }
  settitle: { description: Change my current title, usage: /settitle <titleId> }
  shopadmin: { description: OP edit shop prices, permission: tal.admin, usage: /shopadmin <material> <price> }
  gachatitle: { description: Title gacha, usage: /gachatitle }
  gachaitem: { description: Item gacha, usage: /gachaitem [normal|premium] }
permissions:
  tal.admin: { default: op }
  tal.menu.use: { default: true }
  tal.shop.sell: { default: true }
  tal.title.use: { default: true }
  tal.title.change: { default: true }
  tal.tpa.use: { default: true }
  tal.home.use: { default: true }
  tal.warp.plaza: { default: true }
  tal.warp.arena: { default: true }
